---
name: CI

'on':
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [lint, unit, packer, terraform, ansible]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ matrix.stage == 'lint' || matrix.stage == 'unit' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        if: ${{ matrix.stage == 'lint' || matrix.stage == 'unit' }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run lint
        if: ${{ matrix.stage == 'lint' }}
        run: pre-commit run --all-files

      - name: Run unit tests
        if: ${{ matrix.stage == 'unit' }}
        run: pytest

      - name: Packer validate
        if: ${{ matrix.stage == 'packer' }}
        run: |
          packer init infra/packer
          packer validate infra/packer/*.pkr.hcl

      - name: Terraform validate
        if: ${{ matrix.stage == 'terraform' }}
        run: |
          terraform -chdir=infra init -backend=false
          terraform -chdir=infra validate

      - name: Ansible lint
        if: ${{ matrix.stage == 'ansible' }}
        run: ansible-lint

  trivy:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Trivy scan SOC01 image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: soc01:latest

  release:
    runs-on: ubuntu-latest
    needs: trivy
    steps:
      - uses: actions/checkout@v4
      - name: Upload orchestrator and range.yml example
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            orchestrator
            range.yml.example
